name: Emoji Update

# This workflow is being kept in the repo, but is currently not used, and
# automatic triggering is disabled. It also needs to be updated to use the new
# auth JSON before being re-enabled.
on:
#  push:
#    branches:
#      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: node index.js ${{secrets.SLACK_TOKEN}}
      env:
        CI: true
